### ISSUE TITLE
Cannot move craft with Joystick

### ISSUE THREAD

**Issue by The-King-of-Toasters** [phoboslab/wipeout-rewrite#26] opened 2023-08-16 13:15 UTC
It seems after your work re: controller bindings, the ability to move the ships with the controller was removed. This is with the SDL2 platform, of course.

Edit: bisected to b2e3ae8.

**Comment by enigma9o7** [comment] 2023-08-16 17:21
In my case, the controller still works as before - unless I customize controls in the new menu.  Any button I change in controller settings doesn't work (on new button or old).  The movement still works as I didn't change that.  If I delete the save.dat contoller works (with default buttons) again.

Also during the controller setup, it doesn't recognize my right shoulder button at all.  Seems to recognize everything else.   I'm using cheap usb gamepad (Mafiti GP100).

**Comment by enigma9o7** [comment] 2023-08-17 17:29
I realize now my issue is unrelated to the thread topic, as I'm not using a joystick, only dpad.  

> To clarify: you're able to set the buttons in the options but then cannot use them in the game?

Yes, but I figured out if I restart the game after making button changes, then they work as expected.  The only issue I dunno how to work around is why it ignores my right shoulder, but there's enough other buttons I'm okay without it anyway.

Thanks again for great job, gameplay is great.

**Comment by phoboslab** [comment] 2023-08-17 20:21
> Yes, but I figured out if I restart the game after making button changes, then they work as expected.

Ah, meh. I thought I had fixed that issue. I believe it's caused by the buttons states not set correctly when a new button is bound. I'll look into it.

> The only issue I dunno how to work around is why it ignores my right shoulder

The [mapping in platform_sdl.c](https://github.com/phoboslab/wipeout-rewrite/blob/master/src/platform_sdl.c#L15-L32) is missing some that I (falsely?) assumed to be mostly unused. SDL provides these buttons: https://wiki.libsdl.org/SDL2/SDL_GameControllerButton – I guess the shoulder button on your gamepad is one of the `SDL_CONTROLLER_BUTTON_PADDLE*` ones!? Curious that the left one works though.

Can you maybe add a `printf("button %d", ev.cbutton.button)` [here](https://github.com/phoboslab/wipeout-rewrite/blob/master/src/platform_sdl.c#L96) and check whether it's triggered by this button at all?

**Comment by enigma9o7** [comment] 2023-08-19 20:22
> Can you maybe add a `printf("button %d", ev.cbutton.button)` [here](https://github.com/phoboslab/wipeout-rewrite/blob/master/src/platform_sdl.c#L96) and check

Did it, and I see output in the terminal for other buttons similar to:
`button 3button 0button 0button 9wrote save.dat`
but nothing for right shoulder, and the new 3 second timer just times when I try pushing it.

It does work in other sdl2 games and identifies it as button5, for example dolphin emulator:
![dolphin](https://github.com/phoboslab/wipeout-rewrite/assets/30579733/ab879884-7d64-4a42-80b8-b6c1ead9c3d3)

**Comment by phoboslab** [comment] 2023-08-19 21:47
Button 5 is `SDL_CONTROLLER_BUTTON_GUIDE` which indeed was not mapped.  The above commit fixes this. Can you try again?

(not sure what I was thinking there; I guess we should also use the SDL names for these buttons. I believe the internal names where initially from an old game controller in the browser test of mine...)

If it doesn't work: the `printf()` should have printed `button 5` nevertheless. If you added this statement to the right place and it still didn't print, we're not getting the event from SDL at all.

It should be right here
```
else if (
	ev.type == SDL_CONTROLLERBUTTONDOWN || 
	ev.type == SDL_CONTROLLERBUTTONUP
) {
	printf("button %d\n", ev.cbutton.button);
	...
```

**Comment by enigma9o7** [comment] 2023-08-19 22:06
I updated and modified file again.  Now for buttons that work, it just outputs stuff like "button 0".  But still nothing for the right shoulder.

That tool works, and when I run sdl2-jstest --test 0, and press right shoulder, button 5 gets an X.
```
$ ./sdl2-jstest --list
Found 1 joystick(s)

Joystick Name:     'usb gamepad'
Joystick GUID:     030000001008000001e5000010010000
Joystick Number:    0
Number of Axes:     2
Number of Buttons: 10
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'NEXT SNES Controller'
  Mapping: '030000001008000001e5000010010000,NEXT SNES Controller,a:b2,b:b1,back:b8,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,rightshoulder:b5,righttrigger:b6,start:b9,x:b3,y:b0,platform:Linux,'
```

**Comment by phoboslab** [comment] 2023-08-19 22:27
Well, now I'm a bit confused. When you launch `sdl2-jstest --test 0`, you actually test [joystick events](https://github.com/Grumbel/sdl-jstest/blob/master/src/sdl2-jstest.c#L143) which are apparently different from [gamepad events](https://github.com/Grumbel/sdl-jstest/blob/master/src/sdl2-jstest.c#L317). Why is there two APIs? I guess I have some reading to do...

Does the button work when testing gamepad events? `./sdl2-jstest -g 0`

**Comment by enigma9o7** [comment] 2023-08-19 22:54
Yes, it works that way too.  The output is a bit messier, but it shows a 1 on right shoulder when I press it.

![shot-2023-08-19_15-53-03](https://github.com/phoboslab/wipeout-rewrite/assets/30579733/2ceb4be3-1e56-430a-9ab6-c4e5db4e6f71)

**Comment by mickski56** [comment] 2023-08-19 22:57
Why is there two APIs?
Ancient history the joystick api came first as part of alsa
The event api came later as part of the kernel.
For testing event interface devices use evtest /dev/input/eventXX and testgamecontroller X (which is part of sdl2 don't know whether you get it unless you've built the sdl2 tests)

**Comment by phoboslab** [comment] 2023-08-20 08:00
> The output is a bit messier, but it shows a 1 on right shoulder

Ok, I previously thought that maybe this button would only work through the joystick API. Now I'm wondering how in the hell this button is not registered in the code here.

One last thing: sdl2-jstest uses polling for the gamecontroller test, but it also has some commented out code that uses the event API instead (like we do here). Can you test that again? Switch the comments in [456-457](https://github.com/Grumbel/sdl-jstest/blob/master/src/sdl2-jstest.c#L456-L457) like so:
```c
    test_gamecontroller_events(gamepad);
    // test_gamecontroller_state(gamepad);
```
And remove the `#if 0` in [line 316](https://github.com/Grumbel/sdl-jstest/blob/master/src/sdl2-jstest.c#L316) and the `#endif` in [line 409](https://github.com/Grumbel/sdl-jstest/blob/master/src/sdl2-jstest.c#L409). Thanks for your patience ._.


Thanks mickski56; that puts some perspective on things!

**Comment by enigma9o7** [comment] 2023-08-21 03:20
Still works.  the `-t 0` behaves the same as before, all buttons working.  the `-g 0` has a much cleaner output and still works.

```
bodhi@athlon:~/sdl-jstest/build$ ./sdl2-jstest
Usage: ./sdl2-jstest [OPTION]
List available joysticks or test a joystick.
This programm uses SDL for doing its test instead of using the raw
/dev/input/jsX interface

Options:
  -h, --help             Print this help
  --version              Print version number and exit
  -l, --list             Search for available joysticks and list their properties
  -t, --test JOYNUM      Display a graphical representation of the current joystick state
  -g, --gamecontroller IDX
                         Test GameController
  -e, --event JOYNUM     Display the events that are received from the joystick
  -r, --rumble JOYNUM    Test rumble effects on gamepad JOYNUM

Examples:
  ./sdl2-jstest --list
  ./sdl2-jstest --test 1
bodhi@athlon:~/sdl-jstest/build$ ./sdl2-jstest --list
Found 1 joystick(s)

Joystick Name:     'usb gamepad'
Joystick GUID:     030000001008000001e5000010010000
Joystick Number:    0
Number of Axes:     2
Number of Buttons: 10
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'NEXT SNES Controller'
  Mapping: '030000001008000001e5000010010000,NEXT SNES Controller,a:b2,b:b1,back:b8,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,rightshoulder:b5,righttrigger:b6,start:b9,x:b3,y:b0,platform:Linux,'

bodhi@athlon:~/sdl-jstest/build$ ./sdl2-jstest -g 0
Entering gamecontroller test loop, press Ctrl-c to exit
SDL_CONTROLLERDEVICEADDED which:0
SDL_CONTROLLERBUTTONDOWN controller: 0 button: rightshoulder state: 1
SDL_CONTROLLERBUTTONUP   controller: 0 button: rightshoulder state: 0
```
[sdl2-jstest.c.txt](https://github.com/phoboslab/wipeout-rewrite/files/12391260/sdl2-jstest.c.txt)

**Comment by phoboslab** [comment] 2023-08-21 10:05
The only remaining differences I can see from the implementation here and in sdl-jstest are:
1. We only init `SDL_INIT_GAMECONTROLLER` but not  `SDL_INIT_JOYSTICK` or `SDL_INIT_HAPTIC` (you can change it [here](https://github.com/phoboslab/wipeout-rewrite/blob/master/src/platform_sdl.c#L305) and see if it makes a difference)
2. We're not loading the `gamecontrollerdb.txt` (as in [here](https://github.com/Grumbel/sdl-jstest/blob/master/src/sdl2-jstest.c#L611-L614))

I suspect 2. is the culprit. I'll implement this later today.

**Comment by phoboslab** [comment] 2023-08-21 11:10
Above commit loads the `gamecontrollerdb.txt` (you need to manually download it from [here](https://github.com/gabomdq/SDL_GameControllerDB) and place it in the root directory of this project). Additionally, Joysticks will be initialized. Please try again <3

**Comment by enigma9o7** [comment] 2023-08-21 16:06
WORKS IN GAME!  WOOHOO!  Thanks so much for spending so much time figuring this out!
![shot-2023-08-21_09-06-20](https://github.com/phoboslab/wipeout-rewrite/assets/30579733/9a91c08d-cfc2-4b50-a33f-0ae06f42b84a)

**Closed** 2023-08-21 18:43 UTC
