### ISSUE TITLE
menu, "CONTINUE QUALIFYING OR QUIT" logic is reversed

### ISSUE THREAD

**Issue by mickski56** [phoboslab/wipeout-rewrite#31] opened 2023-08-18 14:24 UTC
Start championship race, finish outside the top 3. A menu appears
CONTINUE QUALIFYING OR QUIT
select qualifying and you go to the main menu, select quit and race restarts.

I've had a bit of a look at the code and can't see anything obviously wrong with it, but I'm not much of a c programmer I'm afraid.

**Comment by phoboslab** [comment] 2023-08-18 16:53
Works correctly for me. I guess it's not very clear, because we're missing the blink effect from the PSX original: the **yellow item is the selected one**. By default "CONTINUE QUALIFYING" will be selected on this menu..

**Comment by phoboslab** [comment] 2023-08-18 17:13
I added the text blink now to disambiguate the current menu item. Closing this issue as I believe this was the cause. Thanks for reporting <3

**Closed by phoboslab** 2023-08-18 17:13 UTC

**Comment by mickski56** [comment] 2023-08-18 17:18
Yes my bad, thanks for looking at this
