### ISSUE TITLE
handling of the ship varies greatly between GL and GLES2 renderer

### ISSUE THREAD

**Issue by SingingBush** [phoboslab/wipeout-rewrite#112] opened 2024-01-24 23:34 UTC
I've noticed that depending on which renderer is used the handling can vary a lot. This may be related to other issues such as #96. I found that when using GLESV2 the ship crashes into the mountain after doing the jump while on GL it lands ok. 

The builds I've run to compare are:

```
cmake -S . -B build/ -DPLATFORM=SDL2 -DRENDERER=GL -DUSE_GLVND=on
cmake --build build/
```

```
cmake -S . -B build/ -DPLATFORM=SDL2 -DRENDERER=GLES2 -DUSE_GLVND=on
cmake --build build/
```

Perhaps it's worth setting up an issue template that asks people to specify operating system, platform & renderer when creating a bug report.

**Comment by phoboslab** [comment] 2024-05-13 08:59
Closing this as 1) I couldn't reproduce the _different_ behavior between renderers and 2) the _wrong_ behavior should be fixed with https://github.com/phoboslab/wipeout-rewrite/issues/96

Please re-open if the issue persists.

**Closed by phoboslab** 2024-05-13 08:59 UTC
